### ISSUE TITLE
Peer Code Review - November 29

### ISSUE THREAD

**Issue by simondebbarma** [mariosknl/form_cloning#3]
# Good job! 🚀
---

**Aesthetic Suggestions**

- Increase spacing around the buttons for `Legal` , `Privacy` and  `Security`.
- Padding on the right of `Sign In` text (including the lock icon) in navbar.

---
<img src="https://media.giphy.com/media/yyZRSvISN1vvW/giphy.gif" width="100%">

**Comment by codecell** [comment]
Nice Job man
just a minor change here in the index.html => 
<div class="footerCaptcha">
           <p class="textCaptcha">Invisible reCAPTCHA by Google **Privacy Policy** and **Terms of Use**.</p></div>
just enclose the highlighted text in anchor tags

**Comment by codecell** [comment]
.container {
  width: 400px;
  height: 590px;
  border: 1px solid #e7dada;
  display: block;
  margin-left: auto;
  margin-right: auto;
  background: white;
  overflow: hidden;
}

form {
  width: 85%;
  margin-left: auto;
  margin-right: auto;
  background: white;
}
-----------------------------
----------------------
shorter notation for writing the margin ;
margin : top right bottom left  (CLOCKWISE)   OR
margin: top/bottom left/right  
or to apply common values on all sides 
margin: value    
so you might want to write 
margin: 0 auto instead

**Comment by simonpeterdebbarma** [comment]
Enclose code snippets in ` or ```

**Comment by dxania** [comment]
1. Nice interface.
2. Neat code
3. It is great that you are making use of various tools while writing your code
4. Make use of markdown elements in your readme. Reference link-> https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet
5. Use clear & consistent commit messages; preferably written in imperative tense. https://chris.beams.io/posts/git-commit/

**Comment by simondebbarma** [comment]
# Difference between *background* and *background-color*
---
https://stackoverflow.com/questions/10205464/what-is-the-difference-between-background-and-background-color



`background` will supercede all previous `background-color`, `background-image`, etc. specifications. It's basically a shorthand, but a reset as well.

I will sometimes use it to overwrite previous `background` specifications in template customizations, where I would want the following:

`background: white url(images/image1.jpg) top left repeat;`

to be the following:

`background: black;`

So, all parameters (`background-image`, `background-position`, `background-repeat`) will reset to their default values.
